### ISSUE TITLE
Are “vue-loader” missing in package.json?

### ISSUE THREAD

**Issue by Liquid-Zhangliquan** [storyblok/bootstrap-nuxt-demo#1]
when I run it,it warn “vue-loader can`t find ”

**Comment by DominikAngerer** [comment]
Hey there! Can you send us the full message you're receiving? Maybe also with a quick screenshot of your terminal!

Best,
Dominik

**Comment by Liquid-Zhangliquan** [comment]
![image](https://user-images.githubusercontent.com/23397455/54809408-2af97700-4cbe-11e9-97c8-67d2e49f5758.png)
![image](https://user-images.githubusercontent.com/23397455/54809424-33ea4880-4cbe-11e9-8fed-9360c4046f81.png)

**Comment by Liquid-Zhangliquan** [comment]
if npm install vue-loader --save
is ok

**Comment by ademarCardoso** [comment]
Hi @Liquid-Zhangliquan, thanks for submitting this issue, I will look at this problem 👍 
---Update
I tested with npm and yarn and did not receive the messages, I tried to reproduce in all ways and it worked for me, if anyone has this problem, please reopen this issue or let me know 👍  :)
